fabrica/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/$', include('usuarios.urls', namespace='usuarios')),
]

usuarios/urls.py
from django.conf.urls import url
from usuarios import views

urlpatterns = [
    url(r'^$', views.pessoaView, name='ponto'),
    # url(r'^/$')
]

usuarios/models.py
from django.db import models


class Pessoa(models.Model):
    name = models.CharField(max_length=100)
    cpf = models.CharField(max_length=100)
    matricula = models.CharField(max_length=100)
    senha = models.CharField(max_length=25)

    def __str__(self):
        return self.name



class Data(models.Model):
    pessoa = models.ForeignKey(Pessoa, related_name='ponto', on_delete=models.CASCADE)
    bateuPonto = models.CharField(max_length=30)

    def __str__(self):
        return str(self.pessoa) + ' - ' + self.bateuPonto

usuarios/forms.py
from django import forms
from usuarios.models import Pessoa

class PessoaForm(forms.ModelForm):
    senha = forms.CharField(widget=forms.PasswordInput, required=True)
    matricula = forms.IntegerField(required=True)
    class Meta:
        model = Pessoa
        fields = ['matricula', 'senha']

    # def is_valid(self):

usuarios/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views import generic
from django.views.generic import View
from .models import Pessoa
from usuarios.forms import PessoaForm
from datetime import datetime
from .models import Pessoa, Data
from django.shortcuts import HttpResponse


def baterPonto(request):
    # now = datetime.datetime.now()
    return render(request, 'usuarios/baterponto.html')

def pessoaView(request):
      if request.method == "POST":
          form = PessoaForm(request.POST)
          if form.is_valid():
             post = form.save(commit=False)
             try:
                 if Pessoa.objects.get(matricula=post.matricula):
                     p1 = Pessoa.objects.get(matricula=post.matricula)
                     if post.senha == p1.senha:
                         successful_login = "Registrado com sucesso"
                         agora = datetime.now()
                         agora = agora.strftime('%d/%m/%Y %H:%M:%S')
                         Data.objects.create(pessoa=p1, bateuPonto=agora)
                         return render(request, 'usuarios/baterponto.html', {'form':form, 'sucesso_message':successful_login})

             except:
                 error_message = "Dados incorretos"
                 return render(request, 'usuarios/baterponto.html', {'form':form, 'error':error_message})

             error_message = "Dados incorretos"
             return render(request, 'usuarios/baterponto.html', {'form':form, 'error':error_message})
      else:
          form = PessoaForm(None)
      return render(request, 'usuarios/baterponto.html', {'form':form})

usuarios/templates/usuarios/baterponto.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=width-device">
    <link rel="stylesheet" href="{% static 'usuarios/css/bootstrap1.css' %}">
    <link rel="stylesheet" href="{% static 'usuarios/css/signin.css' %}">

</head>

<body>

    <div class="container">
        <form class="form-signin" role="form" action="{% url 'usuarios:ponto' %}" method="post">
        {% csrf_token %}
            <div class="form-group">
                <h2 class="form-signin-heading">Login</h2>
                <h3 style="font-size: 120%; color:green;">{{ sucesso_message }}</h3>
                <br>
{#                <input type="text" name="matricula" class="form-control" id="matricula_id" placeholder="Matricula" autofocus>#}
{#                <input type="password" name="password" name="password_id" placeholder="Senha" class="form-control">#}
                <div class="form-control">
                {{ form.as_p }}
                </div>
                <h3 style="font-size: 120%;color:red;">{{ error }}</h3>
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </form>
    </div>
</body>
</html>